"""Generates include/fonts.h: anti-aliased bitmap fonts for the status and
setup screens, made from the Aileron typeface (public domain) that Pillow
bundles.

    pip install pillow
    python tools/make_fonts.py

Each glyph is stored as 4-bit coverage, two pixels per byte, rows
top to bottom, starting on a byte boundary.
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

SIZES = {"FONT_SMALL": 19, "FONT_BODY": 26, "FONT_HEADING": 40}
FIRST, LAST = 32, 126

out = Path(__file__).resolve().parent.parent / "include" / "fonts.h"
lines = [
    "// Generated by tools/make_fonts.py from the Aileron typeface (public domain,",
    "// bundled with Pillow). Don't edit by hand.",
    "#pragma once",
    "#include <stdint.h>",
    "",
    "struct Glyph { uint32_t offset; uint8_t w, h; int8_t x, y; uint8_t advance; };",
    "struct Font { const uint8_t *bits; const Glyph *glyphs; uint8_t first, last, ascent, lineHeight; };",
    "",
]

for name, size in SIZES.items():
    font = ImageFont.load_default(size)
    ascent, descent = font.getmetrics()
    bits, glyphs = bytearray(), []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        left, top, right, bottom = font.getbbox(ch, anchor="ls")
        w, h = max(0, right - left), max(0, bottom - top)
        advance = round(font.getlength(ch))
        offset = len(bits)
        if w and h:
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-left, -top), ch, font=font, fill=255, anchor="ls")
            px = img.load()
            for y in range(h):
                row = [px[x, y] >> 4 for x in range(w)]
                if len(row) % 2:
                    row.append(0)
                bits += bytes((row[i] << 4) | row[i + 1] for i in range(0, len(row), 2))
        glyphs.append((offset, w, h, left, top, advance))

    var = name.lower()
    lines.append(f"static const uint8_t {var}_bits[] = {{")
    for i in range(0, len(bits), 24):
        lines.append("  " + ",".join(f"0x{b:02x}" for b in bits[i:i + 24]) + ",")
    lines.append("};")
    lines.append(f"static const Glyph {var}_glyphs[] = {{")
    for code, g in zip(range(FIRST, LAST + 1), glyphs):
        lines.append(f"  {{{g[0]}, {g[1]}, {g[2]}, {g[3]}, {g[4]}, {g[5]}}},  // {chr(code)!r}")
    lines.append("};")
    lines.append(f"static const Font {name} = {{{var}_bits, {var}_glyphs, {FIRST}, {LAST}, {ascent}, {ascent + descent + size // 5}}};")
    lines.append("")

out.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {out} ({out.stat().st_size // 1024} KB)")
